Repository Nior-Near/BE, pull requests merged in 2024-10, with the labels that each got.

#73 Deploy/72 zero downtime deployment
  .DS_Store
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/nior_near/server/global/infra/HeathCheckController.java
  src/main/java/nior_near/server/global/infra/ProfileCheckController.java
  src/main/java/nior_near/server/global/infra/init.md
  src/main/resources/application.properties
  src/test/java/nior_near/server/global/infra/ProfileCheckControllerTest.java
  src/test/java/nior_near/server/global/infra/ProfileCheckControllerUnitTest.java
Labels: :earth_asia: Deploy

#74 [Feat] - OAuth + JWT 인증 구현
  .DS_Store
  .idea/modules.xml
  build.gradle
  src/main/java/nior_near/server/domain/user/api/MemberController.java
  src/main/java/nior_near/server/domain/user/application/MemberService.java
  src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  src/main/java/nior_near/server/domain/user/application/OAuth2MemberServiceImpl.java
  src/main/java/nior_near/server/domain/user/entity/CustomOAuth2Member.java
  src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  src/main/java/nior_near/server/global/auth/dto/NaverAccessTokenInfoResponseDto.java
  src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
  src/main/java/nior_near/server/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/nior_near/server/global/auth/jwt/JwtProvider.java
  src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
  src/main/resources/application.properties
Labels: :sparkles: Feature

#82 [deploy] : https 적용에 따른 무중단 배포 제거
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy

#78 [Fix] Security 적용 시, h2 접근 예외처리
  src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
  src/main/resources/application.properties
Labels: Fix

#86 [deploy] rds private vpc 로 이동함에 따른 CI/CD 방식 변경
  .github/workflows/deploy.yml
  src/main/java/nior_near/server/global/infra/HealthCheckController.java
Labels: :sparkles: Feature, :earth_asia: Deploy

#88 [deploy/feat] : dev 서버용 dev_deploy 스크립트 추가
  .github/workflows/dev_deploy.yml
Labels: :sparkles: Feature, :earth_asia: Deploy

#89 [deploy] : 필요없는 build 부분 스크립트에서 삭제
  .github/workflows/dev_deploy.yml
Labels: :earth_asia: Deploy, Fix

#90 dev cicd 테스트
  src/main/java/nior_near/server/global/infra/ProfileCheckController.java
Labels: :earth_asia: Deploy

#91 dev cicd 테스트
  src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  src/main/java/nior_near/server/global/infra/ProfileCheckController.java
Labels: :earth_asia: Deploy

#83 Refactor/69 store order features
  src/main/java/nior_near/server/domain/store/api/StoreController.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/domain/store/application/StoreQueryService.java
  src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
  src/main/java/nior_near/server/domain/store/dto/request/CompanyChefRegistrationRequestDto.java
  src/main/java/nior_near/server/domain/store/dto/request/FreelanceChefRegistrationRequestDto.java
  src/main/java/nior_near/server/domain/store/dto/response/ChefRegistrationInfoResponseDto.java
Labels: :sparkles: Feature, :hammer: Refactor

#85 [Fix] 마이페이지, 마이페이지-주문내역, 편지 로그인 적용
  src/main/java/nior_near/server/domain/letter/api/LetterController.java
  src/main/java/nior_near/server/domain/letter/application/LetterService.java
  src/main/java/nior_near/server/domain/letter/application/LetterServiceImpl.java
  src/main/java/nior_near/server/domain/user/api/MemberController.java
  src/main/java/nior_near/server/domain/user/application/MemberService.java
  src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
Labels: Fix

#92 main 브랜치에 추가된 기능 develop 브랜치에 반영
  src/main/java/nior_near/server/domain/letter/api/LetterController.java
  src/main/java/nior_near/server/domain/letter/application/LetterService.java
  src/main/java/nior_near/server/domain/letter/application/LetterServiceImpl.java
  src/main/java/nior_near/server/domain/user/api/MemberController.java
  src/main/java/nior_near/server/domain/user/application/MemberService.java
  src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  src/main/java/nior_near/server/global/util/SmsService.java
Labels: :sparkles: Feature

#93 develop 브랜치 main 브랜치에 반영
  .github/workflows/dev_deploy.yml
  src/main/java/nior_near/server/domain/store/api/StoreController.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/domain/store/application/StoreQueryService.java
  src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
  src/main/java/nior_near/server/domain/store/dto/request/CompanyChefRegistrationRequestDto.java
  src/main/java/nior_near/server/domain/store/dto/request/FreelanceChefRegistrationRequestDto.java
  src/main/java/nior_near/server/domain/store/dto/response/ChefRegistrationInfoResponseDto.java
  src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
Labels: :sparkles: Feature

#94 불필요한 주석 제거 및 iamport 변경
  .github/workflows/deploy.yml
Labels: :gear: Setting, :earth_asia: Deploy

#95 불필요한 주석 제거 및 iamport 관련 설정 변경
  .github/workflows/deploy.yml
Labels: :gear: Setting, :earth_asia: Deploy

#97 [fix] : 요리사 신청하기 기능(니어 요리사 신청하기, 개인 요리사 신청하기) 오류 해결
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
Labels: :lady_beetle: BugFix

#98 [fix] : store 저장 시 member name 이 아니라 nickname 저장으로 변경
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
Labels: :lady_beetle: BugFix

#99 [refactor/feat] : 파일 업로드/삭제 구현 방식 변경, 테스트할 때 사용할 상점 삭제하기 기능 구현
  src/main/java/nior_near/server/domain/store/api/StoreController.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandService.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/domain/store/repository/StoreRepository.java
  src/main/java/nior_near/server/global/common/ResponseCode.java
  src/main/java/nior_near/server/global/util/AwsS3Service.java
  src/main/java/nior_near/server/global/util/FileService.java
Labels: :sparkles: Feature, :lady_beetle: BugFix, :hammer: Refactor

#100 [refactor/feat] : 파일 업로드/삭제 구현 방식 변경, 테스트할 때 사용할 상점 삭제하기 기능 구현
  src/main/java/nior_near/server/domain/store/api/StoreController.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandService.java
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/domain/store/repository/StoreRepository.java
  src/main/java/nior_near/server/global/common/ResponseCode.java
  src/main/java/nior_near/server/global/util/AwsS3Service.java
  src/main/java/nior_near/server/global/util/FileService.java
Labels: :sparkles: Feature, :lady_beetle: BugFix, :hammer: Refactor

#101 [refactor] : 니어 요리사 신청하기, 개인 요리사 신청하기 에러 메시지 개선
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/global/common/ResponseCode.java
Labels: :hammer: Refactor

#102 [refactor] : 니어 요리사 신청하기, 개인 요리사 신청하기 에러 메시지 개선
  src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/nior_near/server/global/common/ResponseCode.java
Labels: :hammer: Refactor

#103 [refactor] : 메뉴 설명 글자수 제한 Valid 제거
  src/main/java/nior_near/server/domain/store/dto/request/MenuAddRequestDto.java
Labels: :hammer: Refactor

#104 Develop
  src/main/java/nior_near/server/domain/store/dto/request/MenuAddRequestDto.java
Labels: :hammer: Refactor

#107 :bug: home api 수정 (mvp 기준 -> 실제 운영 로직 기준)
  src/main/java/nior_near/server/domain/store/api/HomeController.java
  src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
Labels: :lady_beetle: BugFix

#108 Deploy/105 release cicd
  .ebextensions_release/00-makeFiles.config
  .ebextensions_release/01-set-timezone.config
  .github/workflows/release_deploy.yml
  .platform/nginx/conf.d/client_max_body_size.conf
  .platform/nginx/nginx.conf
  Procfile
Labels: :earth_asia: Deploy

#109 [deploy] : 테스트
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#110 [deploy] : 빌드 스크립트 오타 수정
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#112 [deploy] : 배포 시 경로 수정
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#113 [BugFix] home api 수정 (mvp 기준 -> 실제 운영 로직 기준)
  src/main/java/nior_near/server/domain/store/api/HomeController.java
  src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
Labels: :lady_beetle: BugFix

#114 [deploy/fix] : git pull 받아오는 브랜치를 release 로 수정
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#115 [deploy/fix] : deploy 로 이동하는 명령어 절대 경로로 수정
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#116 [deploy] : 테스트
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#117 [deploy] : ssh 접속 키 이름 올바르게 변경
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#118 [deploy] : 키 권한 부여 코드 추가
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#119 [deploy] : scp 라이브러리 사용
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#120 [deploy] : 로그로 오류 확인하기
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#122 [deploy] : 로그로 오류 확인하기
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#123 [deploy] : 테스트
  .github/workflows/release_deploy.yml
Labels: :earth_asia: Deploy

#125 [BugFix] oauth successHandler redirect URI 수정
  src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: :lady_beetle: BugFix

#126 [BugFix] oauth successHandler redirect URI 수정
  src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: :lady_beetle: BugFix

#127 Refactor/69 store order features
  src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  src/main/java/nior_near/server/domain/store/dto/response/HomeResponseDto.java
Labels: :lady_beetle: BugFix

#128 Develop
  src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  src/main/java/nior_near/server/domain/store/dto/response/HomeResponseDto.java
Labels: :lady_beetle: BugFix

#129 [fix] : getName -> getNickname
  src/main/java/nior_near/server/domain/order/application/OrderCommandServiceImpl.java
Labels: :lady_beetle: BugFix

#130 Develop
  src/main/java/nior_near/server/domain/order/application/OrderCommandServiceImpl.java
Labels: :lady_beetle: BugFix

#131 Deploy/87 dev cicid
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#132 Develop
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix, :hammer: Refactor

#133 [deploy] : 빌드 스크립트 properties 생성 과정 추가
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#134 [deploy/fix] : properties 적용하는 방식 변경
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#135 [deploy/fix] : properties 적용하는 방식 변경
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#136 [fix] : Member 테이블 member.getName -> member.getNickname 으로 수정
  src/main/java/nior_near/server/domain/payment/application/PaymentServiceImpl.java
  src/main/java/nior_near/server/global/util/SmsService.java
Labels: :lady_beetle: BugFix

#137 log 설정 추가
  src/main/resources/application.properties
Labels: Fix
