Repository Nior-Near/BE, pull requests merged in 2024-08, with the labels that each got.

#3 Feature/1 add chef application
  server/.gitignore
  server/build.gradle
  server/src/main/java/nior_near/server/ServerApplication.java
  server/src/main/java/nior_near/server/domain/order/dto/init.md
  server/src/main/java/nior_near/server/domain/order/entity/Place.java
  server/src/main/java/nior_near/server/domain/store/api/StoreController.java
  server/src/main/java/nior_near/server/domain/store/api/init.md
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandService.java
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/application/init.md
  server/src/main/java/nior_near/server/domain/store/dto/init.md
  server/src/main/java/nior_near/server/domain/store/dto/request/CompanyChefRegistrationRequestDto.java
  server/src/main/java/nior_near/server/domain/store/dto/request/FreelanceChefRegistrationRequestDto.java
  server/src/main/java/nior_near/server/domain/store/dto/response/ChefRegistrationResponseDto.java
  server/src/main/java/nior_near/server/domain/store/entity/Region.java
  server/src/main/java/nior_near/server/domain/store/entity/Store.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreAuth.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreRegion.java
  server/src/main/java/nior_near/server/domain/store/exception/handler/StoreHandler.java
  server/src/main/java/nior_near/server/domain/store/exception/init.md
  server/src/main/java/nior_near/server/domain/store/repository/AuthRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/PlaceRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/RegionRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/StoreAuthRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/StoreRegionRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/StoreRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/init.md
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
  server/src/main/java/nior_near/server/domain/user/repository/MemberRepository.java
  server/src/main/java/nior_near/server/global/common/AwsS3.java
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
  server/src/main/java/nior_near/server/global/config/AwsS3Config.java
  server/src/main/java/nior_near/server/global/error/handler/AwsS3Handler.java
  server/src/main/java/nior_near/server/global/util/AwsS3Service.java
  server/src/main/java/nior_near/server/global/util/FileService.java
  server/src/main/resources/application.properties
Labels: :sparkles: Feature

#5 Feature/2 add menu
  server/src/main/java/nior_near/server/domain/store/api/StoreController.java
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandService.java
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/request/MenuAddRequestDto.java
  server/src/main/java/nior_near/server/domain/store/dto/response/MenuAddResponseDto.java
  server/src/main/java/nior_near/server/domain/store/entity/Menu.java
  server/src/main/java/nior_near/server/domain/store/entity/Store.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreImage.java
  server/src/main/java/nior_near/server/domain/store/repository/MenuRepository.java
  server/src/main/java/nior_near/server/domain/store/repository/StoreImageRepository.java
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
  server/src/main/java/nior_near/server/global/error/handler/MasterExceptionHandler.java
Labels: :sparkles: Feature

#10 Feature/6 get store
  server/src/main/java/nior_near/server/domain/order/entity/Place.java
  server/src/main/java/nior_near/server/domain/store/api/StoreController.java
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryService.java
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/response/ChefRegistrationResponseDto.java
  server/src/main/java/nior_near/server/domain/store/dto/response/MenuAddResponseDto.java
  server/src/main/java/nior_near/server/domain/store/dto/response/StoreResponseDto.java
  server/src/main/java/nior_near/server/domain/store/entity/Auth.java
  server/src/main/java/nior_near/server/domain/store/entity/Region.java
  server/src/main/java/nior_near/server/domain/store/entity/Store.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreAuth.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreImage.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreRegion.java
Labels: :sparkles: Feature

#11 Feature/1 add chef application
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/request/CompanyChefRegistrationRequestDto.java
  server/src/main/java/nior_near/server/domain/store/dto/request/FreelanceChefRegistrationRequestDto.java
  server/src/main/java/nior_near/server/domain/store/dto/response/StoreResponseDto.java
  server/src/main/java/nior_near/server/domain/store/entity/Store.java
  server/src/main/java/nior_near/server/domain/store/entity/StoreRegion.java
  server/src/main/java/nior_near/server/domain/store/repository/StoreRegionRepository.java
Labels: :hammer: Refactor

#15 Feature 주문하기, 주문 조회하기 기능 추가
  server/src/main/java/nior_near/server/domain/order/api/OrderController.java
  server/src/main/java/nior_near/server/domain/order/api/init.md
  server/src/main/java/nior_near/server/domain/order/application/OrderCommandService.java
  server/src/main/java/nior_near/server/domain/order/application/OrderCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/order/application/OrderQueryService.java
  server/src/main/java/nior_near/server/domain/order/application/OrderQueryServiceImpl.java
  server/src/main/java/nior_near/server/domain/order/application/init.md
  server/src/main/java/nior_near/server/domain/order/dto/request/OrderAddRequestDto.java
  server/src/main/java/nior_near/server/domain/order/dto/response/OrderAddResponseDto.java
  server/src/main/java/nior_near/server/domain/order/dto/response/OrderGetResponseDto.java
  server/src/main/java/nior_near/server/domain/order/entity/Order.java
  server/src/main/java/nior_near/server/domain/order/entity/OrderMenu.java
  server/src/main/java/nior_near/server/domain/order/entity/OrderStatus.java
  server/src/main/java/nior_near/server/domain/order/exception/handler/OrderHandler.java
  server/src/main/java/nior_near/server/domain/order/exception/init.md
  server/src/main/java/nior_near/server/domain/order/repository/OrderMenuRepository.java
  server/src/main/java/nior_near/server/domain/order/repository/OrderRepository.java
  server/src/main/java/nior_near/server/domain/order/repository/init.md
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
Labels: :sparkles: Feature

#14 Feature 메뉴 주문 가능한지도 response 에 담아서 전달
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryService.java
  server/src/main/java/nior_near/server/domain/store/dto/response/StoreResponseDto.java
Labels: :sparkles: Feature

#7 [FEAT] 편지함 CRUD
  server/src/main/java/nior_near/server/domain/letter/api/LetterController.java
  server/src/main/java/nior_near/server/domain/letter/api/init.md
  server/src/main/java/nior_near/server/domain/letter/application/LetterService.java
  server/src/main/java/nior_near/server/domain/letter/application/LetterServiceImpl.java
  server/src/main/java/nior_near/server/domain/letter/application/init.md
  server/src/main/java/nior_near/server/domain/letter/dto/init.md
  server/src/main/java/nior_near/server/domain/letter/dto/request/ThankLetterRequestDto.java
  server/src/main/java/nior_near/server/domain/letter/dto/response/LetterResponseDto.java
  server/src/main/java/nior_near/server/domain/letter/dto/response/ThankLetterResponseDto.java
  server/src/main/java/nior_near/server/domain/letter/entity/Letter.java
  server/src/main/java/nior_near/server/domain/letter/entity/LetterStatus.java
  server/src/main/java/nior_near/server/domain/letter/exception/handler/LetterExceptionHandler.java
  server/src/main/java/nior_near/server/domain/letter/exception/init.md
  server/src/main/java/nior_near/server/domain/letter/repository/LetterRepository.java
  server/src/main/java/nior_near/server/domain/letter/repository/init.md
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
Labels: :sparkles: Feature

#9 [FEAT] 마이페이지 조회 API
  server/.gitignore
  server/src/main/java/nior_near/server/domain/user/api/MemberController.java
  server/src/main/java/nior_near/server/domain/user/api/init.md
  server/src/main/java/nior_near/server/domain/user/application/MemberService.java
  server/src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/application/init.md
  server/src/main/java/nior_near/server/domain/user/dto/init.md
  server/src/main/java/nior_near/server/domain/user/dto/response/MyMemberResponseDto.java
  server/src/main/java/nior_near/server/domain/user/exception/handler/MemberExceptionHandler.java
  server/src/main/java/nior_near/server/domain/user/exception/init.md
  server/src/main/java/nior_near/server/domain/user/repository/init.md
  server/src/main/java/nior_near/server/domain/user/utils/init.md
  server/src/main/resources/application.properties
Labels: :sparkles: Feature

#16 Feature get-place-region
  server/src/main/java/nior_near/server/domain/order/entity/Place.java
  server/src/main/java/nior_near/server/domain/store/api/StoreController.java
  server/src/main/java/nior_near/server/domain/store/application/StoreCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryService.java
  server/src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/response/PlaceRegionGetResponse.java
Labels: :sparkles: Feature

#20 :sparkles: Feat: 지역 리스트 api 구현
  server/src/main/java/nior_near/server/domain/store/api/RegionController.java
  server/src/main/java/nior_near/server/domain/store/application/RegionService.java
  server/src/main/java/nior_near/server/domain/store/application/RegionServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/response/RegionsGetResponseDto.java
  server/src/main/java/nior_near/server/domain/store/repository/RegionRepository.java
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
Labels: :sparkles: Feature

#23 Feature add-order
  server/src/main/java/nior_near/server/domain/order/application/OrderCommandServiceImpl.java
Labels: :sparkles: Feature

#34 30 feat 로그인 기능
  server/.gitignore
  server/build.gradle
  server/src/main/java/nior_near/server/domain/user/api/MemberController.java
  server/src/main/java/nior_near/server/domain/user/application/MemberService.java
  server/src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/application/OAuth2MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/entity/CustomOAuth2Member.java
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
  server/src/main/java/nior_near/server/domain/user/repository/MemberRepository.java
  server/src/main/java/nior_near/server/global/auth/CORSFilater.java
  server/src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  server/src/main/java/nior_near/server/global/auth/dto/NaverAccessTokenInfoResponseDto.java
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
  server/src/main/java/nior_near/server/global/auth/jwt/JwtAuthenticationFilter.java
  server/src/main/java/nior_near/server/global/auth/jwt/JwtProvider.java
  server/src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
  server/src/main/java/nior_near/server/global/common/ResponseCode.java
  server/src/main/resources/application.properties
Labels: :sparkles: Feature

#39 :bug: Fix: 배포서버 쿠키 전달 설정
  server/src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: Fix

#40 :bug: Fix: 배포서버 쿠키 전달 설정#2
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: Fix

#38 [Fix] 감사 인사 로직 수정
  server/src/main/java/nior_near/server/domain/letter/application/LetterServiceImpl.java
  server/src/main/java/nior_near/server/domain/letter/repository/LetterRepository.java
  server/src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
Labels: Fix

#41 :bug: Fix: 배포서버 쿠키 전달 설정#3
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: Fix

#31 Feat: 주문완료 시 문자 전송
  server/.gitignore
  server/build.gradle
  server/src/main/java/nior_near/server/domain/order/application/OrderCommandServiceImpl.java
  server/src/main/java/nior_near/server/domain/payment/api/PaymentController.java
  server/src/main/java/nior_near/server/domain/payment/application/PaymentService.java
  server/src/main/java/nior_near/server/domain/payment/application/PaymentServiceImpl.java
  server/src/main/java/nior_near/server/domain/payment/dto/request/PayStatusRequestDto.java
  server/src/main/java/nior_near/server/domain/payment/dto/response/PayStatusResponseDto.java
  server/src/main/java/nior_near/server/domain/payment/entity/PaymentStatus.java
  server/src/main/java/nior_near/server/global/util/SmsService.java
  server/src/main/resources/application.properties
  server/src/main/resources/templates/paymentTest.html
Labels: :sparkles: Feature

#42 :bug: Fix: member 엔티티 nickname 수정
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
Labels: Fix

#46 :bug: Fix: Home, Regions 부분 수정 && cookie 할당 부분 수정
  server/src/main/java/nior_near/server/domain/store/api/HomeController.java
  server/src/main/java/nior_near/server/domain/store/api/RegionController.java
  server/src/main/java/nior_near/server/domain/store/application/HomeService.java
  server/src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/request/UpdateRegionRequestDto.java
  server/src/main/java/nior_near/server/domain/user/application/MemberService.java
  server/src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/entity/Member.java
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
Labels: Fix

#52 :bug: Delete: 로그인 기능 제거
  server/build.gradle
  server/src/main/java/nior_near/server/domain/store/api/HomeController.java
  server/src/main/java/nior_near/server/domain/store/api/RegionController.java
  server/src/main/java/nior_near/server/domain/store/application/HomeService.java
  server/src/main/java/nior_near/server/domain/store/application/HomeServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/application/RegionService.java
  server/src/main/java/nior_near/server/domain/store/application/RegionServiceImpl.java
  server/src/main/java/nior_near/server/domain/store/dto/response/RegionsGetResponseDto.java
  server/src/main/java/nior_near/server/domain/user/application/MemberService.java
  server/src/main/java/nior_near/server/domain/user/application/MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/application/OAuth2MemberServiceImpl.java
  server/src/main/java/nior_near/server/domain/user/entity/CustomOAuth2Member.java
  server/src/main/java/nior_near/server/global/auth/WebSecurityConfiguration.java
  server/src/main/java/nior_near/server/global/auth/dto/NaverAccessTokenInfoResponseDto.java
  server/src/main/java/nior_near/server/global/auth/handler/OAuth2SuccessHandler.java
  server/src/main/java/nior_near/server/global/auth/jwt/JwtAuthenticationFilter.java
  server/src/main/java/nior_near/server/global/auth/jwt/JwtProvider.java
  server/src/main/java/nior_near/server/global/auth/jwt/TokenParser.java
  server/src/main/resources/application.properties
Labels: :lady_beetle: BugFix

#54 :art: Fix: cors 배포 사이트 처리
  server/src/main/java/nior_near/server/global/config/WebConfig.java
Labels: Fix

#57 [deploy] : github actions 적용 및 폴더 위치 이동
  .github/workflows/deploy.yml
  .idea/dbnavigator.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: :earth_asia: Deploy

#58 [deploy] : application.properties 설정 수정
  .DS_Store
  .github/workflows/deploy.yml
  .idea/BE.iml
Labels: :earth_asia: Deploy

#59 [deploy] : application.properties 관련 설정 경로 변경
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy

#60 [deploy] : application.properties 관련 설정 경로 수정
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy

#61 [deploy] : 빌드 파일 관련 경로 수정
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy

#62 [deploy] : 빌드 파일 관련 경로 수정
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy

#64 [deploy-fix] : 빌드 세팅 수정
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  settings.gradle
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#65 [deploy-fix] : test 에러 로그를 보기 위한 명령어 추가
  .github/workflows/deploy.yml
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#66 [deploy-fix] : Test 의존성 문제 때문에 발생한 것으로 추정
  src/test/java/nior_near/server/ServerApplicationTests.java
Labels: :earth_asia: Deploy, :lady_beetle: BugFix

#68 fix - get store
  .idea/dbnavigator.xml
  .idea/modules.xml
  src/main/java/nior_near/server/domain/order/entity/OrderStatus.java
  src/main/java/nior_near/server/domain/store/application/StoreQueryServiceImpl.java
Labels: Fix
